"""add industry timezone slug editable

Revision ID: 0ec4b247111b
Revises: b2c4e6f8a0d1
Create Date: 2026-04-23 14:09:30.725310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec4b247111b'
down_revision: Union[str, None] = 'b2c4e6f8a0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'industry')
    # ### end Alembic commands ###
