"""tenant-id-in-token-usage

Revision ID: 135c836ecfdd
Revises: 008_add_token_usage
Create Date: 2026-05-04 15:53:11.984681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135c836ecfdd'
down_revision: Union[str, None] = '008_add_token_usage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_logs_channel_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_conversation_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_tenant_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_contact_usage_conversation_id'), table_name='contact_usage')
    op.add_column('token_usage', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_token_usage_business_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_created_at'), table_name='token_usage')
    op.drop_constraint(op.f('token_usage_business_id_fkey'), 'token_usage', type_='foreignkey')
    op.create_foreign_key(None, 'token_usage', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('token_usage', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_usage', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'token_usage', type_='foreignkey')
    op.create_foreign_key(op.f('token_usage_business_id_fkey'), 'token_usage', 'tenants', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_token_usage_created_at'), 'token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_business_id'), 'token_usage', ['business_id'], unique=False)
    op.drop_column('token_usage', 'tenant_id')
    op.create_index(op.f('ix_contact_usage_conversation_id'), 'contact_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_tenant_id'), 'ai_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_conversation_id'), 'ai_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_channel_id'), 'ai_logs', ['channel_id'], unique=False)
    # ### end Alembic commands ###
