"""conversaciones

Revision ID: 28c9d2d34923
Revises: b2c4e6f8a0d1
Create Date: 2026-04-24 16:56:23.862579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28c9d2d34923'
down_revision: Union[str, None] = 'b2c4e6f8a0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_threads', sa.Column('is_group', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('channel_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('is_group', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('group_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('is_status', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('sender_external_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('has_media', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_messages_channel_provider_id', 'messages', ['channel_id', 'provider_message_id'])
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.add_column('tenants', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'industry')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint('uq_messages_channel_provider_id', 'messages', type_='unique')
    op.drop_column('messages', 'raw_payload')
    op.drop_column('messages', 'has_media')
    op.drop_column('messages', 'provider_timestamp')
    op.drop_column('messages', 'sender_name')
    op.drop_column('messages', 'sender_external_id')
    op.drop_column('messages', 'is_status')
    op.drop_column('messages', 'group_id')
    op.drop_column('messages', 'is_group')
    op.drop_column('messages', 'channel_id')
    op.drop_column('chat_threads', 'is_group')
    # ### end Alembic commands ###
