"""sync_models_db_request_id

Revision ID: 4d680c0ca73a
Revises: 139_bot_actions_p15_contracts
Create Date: 2026-05-07 15:16:06.792206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d680c0ca73a'
down_revision: Union[str, None] = '139_bot_actions_p15_contracts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_logs', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.create_index('ix_ai_logs_request_id', 'ai_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_logs_request_id', table_name='ai_logs')
    op.drop_column('ai_logs', 'request_id')
    # ### end Alembic commands ###
