"""modify tenants

Revision ID: a69d78c70b8c
Revises: c09acd32079d
Create Date: 2026-04-23 15:13:37.393564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a69d78c70b8c'
down_revision: Union[str, None] = 'c09acd32079d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_wallets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('balance_tokens', sa.BigInteger(), nullable=False),
    sa.Column('consumed_tokens', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.drop_table('tenant_settings')
    op.add_column('tenant_bot_configs', sa.Column('usage_limits_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('branding_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('features_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'features_jsonb')
    op.drop_column('tenants', 'branding_jsonb')
    op.drop_column('tenant_bot_configs', 'usage_limits_jsonb')
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usage_limits_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('features_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('branding_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_settings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_settings_pkey')),
    sa.UniqueConstraint('tenant_id', name=op.f('tenant_settings_tenant_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('tenant_wallets')
    # ### end Alembic commands ###
